In [1]:
import pandas as pd
import numpy as np

data= pd.read_excel('../../../source/car-data-category-encoding.xlsx', sheet_name='Sheet1')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   class     1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [4]:
data.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

# 2 Create Python functions (one for each of the encoding methods) to accept as inputs a
dataframe and a target column, and return a new dataframe with all columns encoded, except the target column, using the following methods: (Can you create just one function to handle all the below methods, instead of creating separate one for each?) (Which Python module implements all the below methods? Find out)
a. Integer or Ordinal encoding
b. One-hot encoding
c. Binary encoding
d. Target encoding
e. Frequency encoding

In [2]:
from category_encoders import OrdinalEncoder, OneHotEncoder, BinaryEncoder, TargetEncoder
import pandas as pd

def encode_dataframe(df, target_column, method):
    """
    Encodes all columns in the DataFrame except the target column using the specified method.

    Parameters:
        df (pd.DataFrame): The input DataFrame.
        target_column (str): The name of the target column to exclude from encoding.
        method (str): The encoding method to use. Options are:
                      'integer', 'onehot', 'binary', 'target', 'frequency'.

    Returns:
        pd.DataFrame: A new DataFrame with the specified encoding applied.
    """
    encoded_df = df.copy()
    
    if method == 'integer' or method == 'ordinal':
        encoder = OrdinalEncoder(cols=[col for col in df.columns if col != target_column])
        encoded_df = encoder.fit_transform(encoded_df)
    
    elif method == 'onehot':
        encoder = OneHotEncoder(cols=[col for col in df.columns if col != target_column], use_cat_names=True)
        encoded_df = encoder.fit_transform(encoded_df)
    
    elif method == 'binary':
        encoder = BinaryEncoder(cols=[col for col in df.columns if col != target_column])
        encoded_df = encoder.fit_transform(encoded_df)
    
    elif method == 'target':
        encoder = TargetEncoder(cols=[col for col in df.columns if col != target_column])
        encoded_df = encoder.fit_transform(encoded_df, encoded_df[target_column])
    
    elif method == 'frequency':
        for col in df.columns:
            if col != target_column:
                freq = df[col].value_counts() / len(df)
                encoded_df[col] = df[col].map(freq)
    
    else:
        raise ValueError("Unsupported encoding method. Choose from 'integer', 'onehot', 'binary', 'target', or 'frequency'.")
    
    return encoded_df

In [6]:
# Example usage:
encoded_data_one_integer = encode_dataframe(data, target_column='class', method='integer')

encoded_data_one_integer.head()

buying  maint  doors  persons  lug_boot  safety  class
0       1      1      1        1         1       1  unacc
1       1      1      1        1         1       2  unacc
2       1      1      1        1         1       3  unacc
3       1      1      1        1         2       1  unacc
4       1      1      1        1         2       2  unacc

In [7]:
# Example usage:
encoded_data_one_hot = encode_dataframe(data, target_column='class', method='onehot')

encoded_data_one_hot.head()

buying_vhigh  buying_high  buying_med  buying_low  maint_vhigh  maint_high  \
0             1            0           0           0            1           0   
1             1            0           0           0            1           0   
2             1            0           0           0            1           0   
3             1            0           0           0            1           0   
4             1            0           0           0            1           0   

   maint_med  maint_low  doors_2  doors_3  ...  persons_2  persons_4  \
0          0          0        1        0  ...          1          0   
1          0          0        1        0  ...          1          0   
2          0          0        1        0  ...          1          0   
3          0          0        1        0  ...          1          0   
4          0          0        1        0  ...          1          0   

   persons_more  lug_boot_small  lug_boot_med  lug_boot_big  safety_low  \
0             0               1             0             0           1   
1             0               1             0             0           0   
2             0               1             0             0           0   
3             0               0             1             0           1   
4             0               0             1             0           0   

   safety_med  safety_high  class  
0           0            0  unacc  
1           1            0  unacc  
2           0            1  unacc  
3           0            0  unacc  
4           1            0  unacc  

[5 rows x 22 columns]

In [8]:
# Example usage:
encoded_data_binary = encode_dataframe(data, target_column='class', method='binary')

encoded_data_binary.head()

buying_0  buying_1  buying_2  maint_0  maint_1  maint_2  doors_0  doors_1  \
0         0         0         1        0        0        1        0        0   
1         0         0         1        0        0        1        0        0   
2         0         0         1        0        0        1        0        0   
3         0         0         1        0        0        1        0        0   
4         0         0         1        0        0        1        0        0   

   doors_2  persons_0  persons_1  lug_boot_0  lug_boot_1  safety_0  safety_1  \
0        1          0          1           0           1         0         1   
1        1          0          1           0           1         1         0   
2        1          0          1           0           1         1         1   
3        1          0          1           1           0         0         1   
4        1          0          1           1           0         1         0   

   class  
0  unacc  
1  unacc  
2  unacc  
3  unacc  
4  unacc

In [9]:
# Example usage:
encoded_data_target = encode_dataframe(data, target_column='class', method='target')

encoded_data_target.head()

buying     maint     doors  persons  lug_boot    safety  class
0  1.666667  1.666667  1.613426      2.0  1.598958  2.000000  unacc
1  1.666667  1.666667  1.613426      2.0  1.598958  1.307292  unacc
2  1.666667  1.666667  1.613426      2.0  1.598958  1.352431  unacc
3  1.666667  1.666667  1.613426      2.0  1.532986  2.000000  unacc
4  1.666667  1.666667  1.613426      2.0  1.532986  1.307292  unacc

# 3 Using each of the above encoded dataframes carry out the following steps:

a. Split the available data into train / test sets
b. Create a classification model (e.g. Random Forest Classification) to predict the “class” using all the other columns.
c. Derive the test and train metrics for each class: Precision, recall, F1-score, overall accuracy, and save these metrics in a dataframe.
d. Create and print the Confusion Matrix.

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import pandas as pd

def evaluate_model(encoded_df, target_column):
    """
    Splits the data, trains a Random Forest Classifier, and evaluates the model.
    
    Parameters:
        encoded_df (pd.DataFrame): The encoded DataFrame.
        target_column (str): The target column name.
    
    Returns:
        pd.DataFrame: DataFrame containing precision, recall, F1-score, and accuracy.
        np.ndarray: Confusion matrix.
    """
    # Split data into features (X) and target (y)
    X = encoded_df.drop(columns=[target_column])
    y = encoded_df[target_column]
    
    # Split into train and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    
    # Train Random Forest Classifier
    model = RandomForestClassifier(random_state=42)
    model.fit(X_train, y_train)
    
    # Make predictions
    y_pred = model.predict(X_test)
    
    # Calculate metrics
    report = classification_report(y_test, y_pred, output_dict=True)
    metrics_df = pd.DataFrame(report).transpose()
    overall_accuracy = accuracy_score(y_test, y_pred)
    metrics_df.loc['accuracy'] = [overall_accuracy, None, None, None]
    
    # Confusion Matrix
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    return metrics_df, conf_matrix

In [21]:
# Example usage for each encoded DataFrame

# Integer/Ordinal Encoding
metrics_integer, conf_matrix_integer = evaluate_model(encoded_data_one_integer, target_column='class')
print("Metrics for Integer/Ordinal Encoding:")
metrics_integer


Metrics for Integer/Ordinal Encoding:


precision    recall  f1-score  support
acc            0.931034  0.915254  0.923077    118.0
good           0.761905  0.842105  0.800000     19.0
unacc          0.988858  0.991620  0.990237    358.0
vgood          0.913043  0.875000  0.893617     24.0
accuracy       0.963391       NaN       NaN      NaN
macro avg      0.898710  0.905995  0.901733    519.0
weighted avg   0.963897  0.963391  0.963535    519.0

In [22]:
print("\nConfusion Matrix:")
conf_matrix_integer


Confusion Matrix:


array([[108,   5,   4,   1],
       [  2,  16,   0,   1],
       [  3,   0, 355,   0],
       [  3,   0,   0,  21]])

In [23]:

# Binary Encoding
metrics_binary, conf_matrix_binary = evaluate_model(encoded_data_binary, target_column='class')
print("\nMetrics for Binary Encoding:")
metrics_binary


Metrics for Binary Encoding:


precision    recall  f1-score  support
acc            0.729323  0.822034  0.772908    118.0
good           0.285714  0.210526  0.242424     19.0
unacc          0.961326  0.972067  0.966667    358.0
vgood          0.900000  0.375000  0.529412     24.0
accuracy       0.882466       NaN       NaN      NaN
macro avg      0.719091  0.594907  0.627853    519.0
weighted avg   0.881009  0.882466  0.875880    519.0

In [25]:
print("\nConfusion Matrix:")
conf_matrix_binary


Confusion Matrix:


array([[ 97,   7,  14,   0],
       [ 14,   4,   0,   1],
       [ 10,   0, 348,   0],
       [ 12,   3,   0,   9]])

In [26]:
# Target Encoding
metrics_target, conf_matrix_target = evaluate_model(encoded_data_target, target_column='class')
print("\nMetrics for Target Encoding:")
metrics_target


Metrics for Target Encoding:


precision    recall  f1-score  support
acc            0.940678  0.940678  0.940678    118.0
good           0.800000  0.842105  0.820513     19.0
unacc          0.994382  0.988827  0.991597    358.0
vgood          0.920000  0.958333  0.938776     24.0
accuracy       0.971098       NaN       NaN      NaN
macro avg      0.913765  0.932486  0.922891    519.0
weighted avg   0.971616  0.971098  0.971314    519.0

In [27]:

print("\nConfusion Matrix:")
conf_matrix_target


Confusion Matrix:


array([[111,   4,   2,   1],
       [  2,  16,   0,   1],
       [  4,   0, 354,   0],
       [  1,   0,   0,  23]])